[env]
platform = espressif32@7.0.1
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; --- N16R8 : 16 Mo Flash + 8 Mo PSRAM Octal ---
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs

build_flags =
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -O2
    -D CONFIG_ARDUHAL_LOG_DEFAULT_LEVEL=1
    -D TF_LITE_STATIC_MEMORY
    -std=gnu++17
    -fno-exceptions
    -fno-rtti
    -fno-use-cxa-atexit
    -Wno-error=placement-new
    -w

lib_deps =
    TensorFlowLite_ESP32
    knolleary/PubSubClient @ 2.8.0
    bblanchon/ArduinoJson @ 6.21.6

; ---- PRODUCTION : CNN 1D seul (demo + captures) ----
[env:esp32s3_cnn]
build_flags = ${env.build_flags} -D ENABLE_MLP=0

; ---- BENCHMARK : MLP seul (mesures Tableau 5.2) ----
[env:esp32s3_mlp]
build_flags = ${env.build_flags} -D ENABLE_MLP=1 -D BENCH_MLP_ONLY=1
